source 'https://rubygems.org'

gem 'jekyll'
gem 'kramdown'
gem 'coderay'
gem 'rake'
gem 'thor'
gem 'activesupport'
gem 'stringex'
gem 'jekyll-mentions'
gem 'jemoji'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'github-pages'
